# 本文件收录了全功能 RMVL 的编译工具链，欢迎开发者贡献自己的工具链

- name: "u22"
  image: "registry.cn-hangzhou.aliyuncs.com/cv-rmvl/rmvl-u22:latest"
  options:
  - "-e LANG=zh_CN.UTF-8"
- name: "u24"
  image: "registry.cn-hangzhou.aliyuncs.com/cv-rmvl/rmvl-u24:latest"
  options:
  - "-e LANG=C.UTF-8"
- name: "tlt507"
  description: "Tronlong T507 的 EtherCAT 环境支持，请使用 ~/LinuxSDK/toolchain.cmake 进行交叉编译"
  image: "registry.cn-hangzhou.aliyuncs.com/cv-rmvl/ethercat:latest"
  options:
  - "-e LANG=C.UTF-8"