name: 1.x in Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu1804-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u18.yml@main
  ubuntu2004-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u20.yml@main
  ubuntu2204-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u22.yml@main
  ubuntu2404-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u24.yml@main
