name: 1.x in Linux

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  cmake-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-install.yml@main
  minimal-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-lowest.yml@main
  generic-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-generic.yml@main
  gcc14-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u24.yml@main
